import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import { onAuthStateChanged } from 'firebase/auth'
// import auth from './firebase'
// import { useEffect } from 'react'
// import Router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Netflix-Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

// // RootLayout.jsx
// "use client"
// import React, { useEffect } from 'react';
// // import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import { getAuth, onAuthStateChanged, signOut } from 'firebase/auth';
// import Router from 'next/router';
// import app from './firebase'
// import MoviesHead from './movies-page/_components/movieshead';


// const inter = Inter({ subsets: ['latin'] });

// // export const metadata: Metadata = {
// //   title: 'Netflix-Clone',
// //   description: 'Generated by create next app',
// // };

// const RootLayout = ({ children }: { children: React.ReactNode }) => {
//   useEffect(() => {
//     const auth = getAuth();

//     const unsubscribe = onAuthStateChanged(auth, (user) => {
//       if (!user) {
//         Router.push('/landing-page');
//       }
//     });

//     return () => {
//       unsubscribe();
//     };
//   }, []);

//   const handleLogout = async () => {
//     const auth = getAuth();
//     try {
//       await signOut(auth);
//       Router.push('/landing-page');
//     } catch (error) {
//       const errorMessage = (error as Error).message;
//       console.error('Logout error:', errorMessage);
//     }
//   };

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <MoviesHead handleLogout={handleLogout} />
//       </body>
//     </html>
//   );
// };

// export default RootLayout;
