"use client"
import React, { useEffect } from 'react';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { useRouter } from 'next/navigation';
import {auth} from './firebase'
const inter = Inter({ subsets: ['latin'] });
// export const metadata: Metadata = {
//   title: 'Netflix-Clone',
//   description: 'Generated by create next app',
// };
const RootLayout = ({ children }: { children: React.ReactNode }) => {
const router=useRouter()
useEffect(() => {
	const unsubscribe = onAuthStateChanged(auth, (user) => {
	if (!user) {
		router.push('/landing-page');
	}
	});
	return () => {
	unsubscribe();
	};
}, []);
return (
		<html lang="en">
		<body className={inter.className}>{children}</body>
		</html>
	)
};
export default RootLayout;
